//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRepuesto
    {
        public int IdDetalle { get; set; }
        public int IdRepuesto { get; set; }
        public int IdOrden { get; set; }
        public int Cantidad { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual OrdenServicio OrdenServicio { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
