//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenServicio()
        {
            this.DetalleRepuesto = new HashSet<DetalleRepuesto>();
        }
    
        public int IdOrden { get; set; }
        public Nullable<int> IdTecnico { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRepuesto> DetalleRepuesto { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
